### ISSUE TITLE
Incorrect behavior of `thisConsensusTime()` on ALGO connector.

### ISSUE THREAD

**Issue by flyingleafe** [reach-sh/reach-lang#855] opened 2022-04-26 13:53 UTC
**Describe the error**

I am trying to implement a simple vesting contract which releases portions of money to the participant via API depending on the time of API call. Using `thisConsensusTime()` in the call leads to the error on the attempt to release a portion of the money after the second non-zero release:

```
$ reach run
Sending build context to Docker daemon  77.31kB
Step 1/3 : FROM reachsh/runner:0.1.10
 ---> 855c52c15748
Step 2/3 : COPY . /app
 ---> Using cache
 ---> 5833825ac0e9
Step 3/3 : CMD ["index"]
 ---> Using cache
 ---> a98e87d4cdf7
Successfully built a98e87d4cdf7
Successfully tagged reachsh/reach-app-time-bugs:0.1.10
Creating 2022-04-26t13-45-04z-ygsr_reach-app-time-bugs_run ... done

> index
> node --experimental-modules --unhandled-rejections=strict index.mjs

Deploying contract with params: {"amount":1000000,"start":929,"duration":50}
Starting queries...
Waited until 909, current time 914; released 0 (total 0)
Waited until 919, current time 938; released 180000 (total 180000)
/stdlib/dist/cjs/shared_impl.js:306
                            fail(new Error("".concat(bl, " errored with ").concat(err)));
                                 ^

Error: release errored with Error: bigNumberify: -180000 out of range [0, 18446744073709551615] at internal
    at /stdlib/dist/cjs/shared_impl.js:306:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERROR: 1
```

The negative value which was attempted to be returned from the API method callback is always equal to the total amount of money released previously with the minus sign. This might happen if consecutive calls to `thisConsensusTime()` do not necessarily return non-decreasing values (see the link to code below).

The same code runs without issue and behaves as expected on ETH connector. Using `lastConsensusTime()` instead of `thisConsensusTime()` fixes the error and the contract runs normally, but its logic of course changes.

**To Reproduce**

The code to reproduce is here: https://github.com/MetaLabsOG/reach-issues/tree/main/time-bugs

**Expected behavior**

The code should run without issues, similarly to how it behaves on ETH connector.

**Extra information**

```
$ reach version
reach 0.1.10

$ reach hashes
reach-cli: b3269997
reach: b3269997
react-runner: b3269997
rpc-server: b3269997
runner: b3269997
devnet-algo: b3269997
devnet-cfx: b3269997
devnet-eth: b3269997
```

**Comment by jeapostrophe** [comment] 2022-04-26 14:05
Thanks! I'll look at this

**Comment by flyingleafe** [comment] 2022-05-04 17:21
@jeapostrophe would you be able to provide any comments on why this happens/ETA?

**Comment by jeapostrophe** [comment] 2022-05-04 17:32
I'm sorry, I haven't had time to investigate yet. But I will very soon!

**Comment by jeapostrophe** [comment] 2022-05-07 20:48
FYI, I have a PR in CI testing that fixes this. It is just a problem with the Algorand simulator for trying to get composability. I adjusted your program a little for testing.

**Comment by flyingleafe** [comment] 2022-05-13 14:28
@jeapostrophe As far as I understood, the fix above has been merged in the current master in the beginning of the week and is now included into the `latest` version of Reach (`c0bba7d2`). However, the issue in my example is not solved, I still get this error:

```
Deploying contract with params: {"amount":1000000,"start":133,"duration":50}
Starting queries...
Waited until 113, current time 118; released 0 (total 0)
Waited until 123, current time 179; released 920000 (total 920000)
/stdlib/dist/cjs/shared_impl.js:315
                            fail(new Error("".concat(bl, " errored with ").concat(err)));
                                 ^

Error: release errored with Error: bigNumberify: -820000 out of range [0, 18446744073709551615] at internal
    at /stdlib/dist/cjs/shared_impl.js:315:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERROR: 1
```

The difference in the behavior after fix is only the following: the returned negative number does not seem to be always equal to the previously released amount.

**Comment by jeapostrophe** [comment] 2022-05-14 15:31
Can you look at the difference between your program and my test:

https://github.com/reach-sh/reach-lang/tree/master/examples/pr855

?

**Comment by flyingleafe** [comment] 2022-05-20 11:10
@jeapostrophe Sorry for a delayed reply. Your test does not work on my machine as well (Reach version `c0bba7d2`).

Firstly, it does not compile because of repeated `.invariant` call:

```
reachc: error[RE0025]: invariant is not a field of <SLV_Form>. Did you mean: ["api","api_","define","case","paySpec"]

  ./index.rsh:37:6:dot

  37|     .invariant(releasable(thisConsensusTime()) >= 0)

For further explanation of this error, see: https://docs.reach.sh/rsh/errors/#RE0025

CallStack (from HasCallStack):
  expect_throw, called at src/Reach/Eval/Core.hs:359:3 in reach-0.1.10-BBxOY8syJEbKiyuQY4llVC:Reach.Eval.Core
  expect_, called at src/Reach/Eval/Core.hs:367:17 in reach-0.1.10-BBxOY8syJEbKiyuQY4llVC:Reach.Eval.Core
  expect_t, called at src/Reach/Eval/Core.hs:1524:16 in reach-0.1.10-BBxOY8syJEbKiyuQY4llVC:Reach.Eval.Core
```

Secondly, when I merge two invariant calls together and make it compile, it still fails on some release call (not necessarily the first one), and all the subsequent ones, since your code catches the exceptions:

**Example 1**
```
Sending build context to Docker daemon  41.47kB
Step 1/3 : FROM reachsh/runner:0.1.10
 ---> f972e3b25bab
Step 2/3 : COPY . /app
 ---> Using cache
 ---> 89a1f50224e5
Step 3/3 : CMD ["index"]
 ---> Using cache
 ---> 5170522041b6
Successfully built 5170522041b6
Successfully tagged reachsh/reach-app-pr855:0.1.10
Creating 2022-05-20t10-58-54z-fov7_reach-app-pr855_run ... done

> index
> node --experimental-modules --unhandled-rejections=strict index.mjs

Starting queries...
WAITED {
  start: BigNumber { _hex: '0xdc', _isBigNumber: true },
  end: BigNumber { _hex: '0xfa', _isBigNumber: true },
  amount: BigNumber { _hex: '0x05f5e100', _isBigNumber: true },
  total: BigNumber { _hex: '0x00', _isBigNumber: true },
  moment: BigNumber { _hex: '0xd2', _isBigNumber: true },
  released: BigNumber { _hex: '0x00', _isBigNumber: true },
  resTime: BigNumber { _hex: '0xcc', _isBigNumber: true }
}
CAUGHT Error: release errored with Error: API call failed: {
  "type": "signAndPost",
  "e": {
    "status": 400,
    "response": {
      "message": "TransactionPool.Remember: transaction RCUUT5EUZOLAUZPMGJ75EMQTHSU25YEO7P33S6DMXFHEDLOUHJRQ: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
    }
  },
  "es": "Error: Network request error. Received status 400: TransactionPool.Remember: transaction RCUUT5EUZOLAUZPMGJ75EMQTHSU25YEO7P33S6DMXFHEDLOUHJRQ: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
}
    at /stdlib/dist/cjs/shared_impl.js:315:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
CAUGHT Error: release errored with Error: API call failed: {
  "type": "signAndPost",
  "e": {
    "status": 400,
    "response": {
      "message": "TransactionPool.Remember: transaction RCUUT5EUZOLAUZPMGJ75EMQTHSU25YEO7P33S6DMXFHEDLOUHJRQ: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
    }
  },
  "es": "Error: Network request error. Received status 400: TransactionPool.Remember: transaction RCUUT5EUZOLAUZPMGJ75EMQTHSU25YEO7P33S6DMXFHEDLOUHJRQ: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
}
    at /stdlib/dist/cjs/shared_impl.js:315:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
CAUGHT Error: release errored with Error: API call failed: {
  "type": "signAndPost",
  "e": {
    "status": 400,
    "response": {
      "message": "TransactionPool.Remember: transaction RCUUT5EUZOLAUZPMGJ75EMQTHSU25YEO7P33S6DMXFHEDLOUHJRQ: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
    }
  },
  "es": "Error: Network request error. Received status 400: TransactionPool.Remember: transaction RCUUT5EUZOLAUZPMGJ75EMQTHSU25YEO7P33S6DMXFHEDLOUHJRQ: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
}
    at /stdlib/dist/cjs/shared_impl.js:315:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
CAUGHT Error: release errored with Error: API call failed: {
  "type": "signAndPost",
  "e": {
    "status": 400,
    "response": {
      "message": "TransactionPool.Remember: transaction 7LJATM2EVZHNSRTNU4Q6YT5CO53DHK2O5AKAPBGVNUJSVTRB6OZA: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
    }
  },
  "es": "Error: Network request error. Received status 400: TransactionPool.Remember: transaction 7LJATM2EVZHNSRTNU4Q6YT5CO53DHK2O5AKAPBGVNUJSVTRB6OZA: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
}
    at /stdlib/dist/cjs/shared_impl.js:315:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Example 2**
```
Sending build context to Docker daemon  41.47kB
Step 1/3 : FROM reachsh/runner:0.1.10
 ---> f972e3b25bab
Step 2/3 : COPY . /app
 ---> Using cache
 ---> 3d807cf0e9f9
Step 3/3 : CMD ["index"]
 ---> Using cache
 ---> 56f71444a67b
Successfully built 56f71444a67b
Successfully tagged reachsh/reach-app-pr855:0.1.10
Creating 2022-05-20t11-05-38z-y81m_reach-app-pr855_run ... done

> index
> node --experimental-modules --unhandled-rejections=strict index.mjs

Starting queries...
WAITED {
  start: BigNumber { _hex: '0x0184', _isBigNumber: true },
  end: BigNumber { _hex: '0x01a2', _isBigNumber: true },
  amount: BigNumber { _hex: '0x05f5e100', _isBigNumber: true },
  total: BigNumber { _hex: '0x00', _isBigNumber: true },
  moment: BigNumber { _hex: '0x017a', _isBigNumber: true },
  released: BigNumber { _hex: '0x00', _isBigNumber: true },
  resTime: BigNumber { _hex: '0x0174', _isBigNumber: true }
}
WAITED {
  start: BigNumber { _hex: '0x0184', _isBigNumber: true },
  end: BigNumber { _hex: '0x01a2', _isBigNumber: true },
  amount: BigNumber { _hex: '0x05f5e100', _isBigNumber: true },
  total: BigNumber { _hex: '0x02255100', _isBigNumber: true },
  moment: BigNumber { _hex: '0x0184', _isBigNumber: true },
  released: BigNumber { _hex: '0x02255100', _isBigNumber: true },
  resTime: BigNumber { _hex: '0x0196', _isBigNumber: true }
}
CAUGHT Error: release errored with Error: bigNumberify: -18000000 out of range [0, 18446744073709551615] at internal
    at /stdlib/dist/cjs/shared_impl.js:315:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
CAUGHT Error: release errored with Error: bigNumberify: -16000000 out of range [0, 18446744073709551615] at internal
    at /stdlib/dist/cjs/shared_impl.js:315:34
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
CAUGHT Error: release errored with Error: API call failed: {
  "type": "signAndPost",
  "e": {
    "status": 400,
    "response": {
      "message": "TransactionPool.Remember: transaction YQQVCKPC5A24J6DINIJWZP4QH5PAW45OIBZOGAFYZUZ5452G7GFA: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
    }
  },
  "es": "Error: Network request error. Received status 400: TransactionPool.Remember: transaction YQQVCKPC5A24J6DINIJWZP4QH5PAW45OIBZOGAFYZUZ5452G7GFA: logic eval error: assert failed pc=415. Details: pc=415, opcodes=pushint 5\n==\nassert\n"
}
    at /stdlib/dist/cjs/shared_impl.js:315:34
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

As you can see, I still get the same error on your example, but in a less consistent way, and sometimes I get `TransactionPool.Remember` error instead. The differences between our examples, if any, apparently do not matter.

**Comment by flyingleafe** [comment] 2022-05-20 11:34
@jeapostrophe Updated Reach to the current latest (`2604daf0`) just in case. In this version repeated invariants compile, but I still see the same behaviour in runtime. As before, only on `ALGO` connector, everything works on `ETH`.

On the other notice, I see that setting the `REACH_CONNECTOR_MODE` env var on my machine stopped overriding `reach config` in version `2604daf0`. I had to re-run `reach config` in order to test behaviour on two different networks.

**Comment by flyingleafe** [comment] 2022-05-26 15:36
@jeapostrophe bump, any hope that could be resolved in the near future?

**Comment by jeapostrophe** [comment] 2022-05-28 15:21
I went and looked at your code again and I see that you haven't changed it at all based on my suggestions in my encoding of your example --- https://github.com/reach-sh/reach-lang/blob/master/examples/pr855/index.mjs

I think the source of the problem is that I don't understand what you think your program is supposed to do.

The error is that you don't know `curTime - start` is always non-negative and sometimes it is not, right?

**Comment by jeapostrophe** [comment] 2022-05-28 15:59
I did some more investigation and may have a lead. On our clients `thisConsensusTime()` comes from the Indexer's `health` call --- https://developer.algorand.org/docs/rest-apis/indexer/#healthcheck --- and we've observed that sometimes it spuriously returns old values.

**Comment by flyingleafe** [comment] 2022-05-28 23:16
@jeapostrophe 
> I went and looked at your code again and I see that you haven't changed it at all based on my suggestions in my encoding of your example

I did not change my example accordingly to yours, since (as I said) I have done testing of newer Reach versions directly on __your__ example, and still observed the same errors. Do you observe the same errors when you try to run your test on ALGO connector?

>  I think the source of the problem is that I don't understand what you think your program is supposed to do.

My program is supposed to simply send 0 or more tokens to the user on each `release` API call. The total amount of vested money grows non-decreasingly with time (accordingly to the piecewise-linear `vested` function). On each call, a user should receive the amount of money equal to `vested(curTime) - alreadyReleased`, where `alreadyReleased` is the total sum of all previous money releases. It is easy to see that the value `vested(curTime) - alreadyReleased` is always >= 0, __if__ the value of `curTime` (which is `thisConsensusTime()` in your and my code) never decreases between calls. 

The value `curTime - start` certainly __can__ be negative in the beginning of the contract's lifecycle. But if it is, it should also mean that it was also negative for all previous contract calls, and therefore `alreadyReleased = 0`.

**Comment by flyingleafe** [comment] 2022-05-29 12:46
>  On our clients thisConsensusTime() comes from the Indexer's health call

Wait, but in the __contract code__ `thisConsensusTime()` cannot be tied to the indexer call. Do I understand correctly that return values from the API calls on ALGO connector are constructed not directly from the changes in the contract state, but rather from the contract simulation on JS backend? And that there is no such problem on ETH since on ETH functions explicitly return value which can be used directly?

**Comment by jeapostrophe** [comment] 2022-05-30 13:52
In the contract code, `thisConsensusTime()` is based on `global Round` in TEAL.

However, on Algorand, before a client sends a transaction, they have to predict what resources the program will use based on the data they are giving it. For example, the program might need to mint a token, so it needs to have funds to do so; or the program might look at a user's local storage.

In Reach, we do this prediction by having the client simulate the contract's code first, record what resources are used, and then send them to the network. The error you are seeing is during that simulation. Your JS client is running `curTime - start` and getting a negative number. If you were to send this transaction to the network, you wouldn't get an error.

Now, when Reach creates its simulation, it will optimize away values and computations that can't influence resources. But, your program's resources depends on the computation. If a user releases the last amount of ALGOs, then the `while` loop ends, and that will then determine whether the program is going to halt on not. When it halts, we need to close the accounts, and that costs a fee.

So, I think there are two solutions to this:
1. Me: Figure out how to get the indexer to always give accurate round times.
2. You: Change your code so that closing the program is a separate step.

I don't actually know that either of these will work, but I think they will.

**Comment by jeapostrophe** [comment] 2022-11-02 17:56
Closing because the thread died and the problem was probably fixed in the interim by general changes, `enforce`, or `sim*` options on remote functions

**Closed by jeapostrophe** 2022-11-02 17:56 UTC
