### ISSUE TITLE
Internal Server Error for url: https://127.0.0.1:3000/backend/Alice

### ISSUE THREAD

**Issue by rfustino** [reach-sh/reach-lang#263] opened 2021-09-01 20:53 UTC
When running RPC Python in two IDEs or in two different directories sometimes in the same IDE, each with venv,  I will get this error below. The question is how do I recover from this without rebooting my machine?   reach clean, reach reset, reach docker-reset and netstat -vanp tcp | grep 3000 with lsof -1 tcp:3000 all do not work.  

I am getting error when trying to run python from more than one solution

```Bob accepts the wager of 5
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "./index.py", line 50, in play_alice
    rpc_callbacks(
  File "/Users/algorand/Documents/GitHub/Reach-Morra-Game/morrademo/client-py/venv/lib/python3.8/site-packages/reach_rpc/__init__.py", line 66, in rpc_callbacks
    p     = rpc(m, arg, vals, meths)
  File "/Users/algorand/Documents/GitHub/Reach-Morra-Game/morrademo/client-py/venv/lib/python3.8/site-packages/reach_rpc/__init__.py", line 59, in rpc
    ans.raise_for_status()
  File "/Users/algorand/Documents/GitHub/Reach-Morra-Game/morrademo/client-py/venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://127.0.0.1:3000/backend/Alice```

**Comment by jeapostrophe** [comment] 2021-09-02 15:44
Thanks, I've scheduled this :)

**Comment by mattaudesse** [comment] 2021-09-16 21:16
@rfustino I'm afraid I can't reproduce or troubleshoot this without some more details about your setup + steps.

**If you're still having trouble with this please let us know the exact steps you're following, with as much detail as possible, and share the code where you're able to see it break.**

> The question is how do I recover from this without rebooting my machine? reach clean, reach reset, reach docker-reset and netstat -vanp tcp | grep 3000 with lsof -1 tcp:3000 all do not work.

`reach docker-reset` should nuke anything Docker's doing and make rebooting unnecessary, so I suspect the steps you're following to trigger this might instead make it appear to be stuck somehow(?)

Based on your stack trace it looks like you're using the https://github.com/algorand-devrel/Reach-Morra-Game repo but I don't see a `morrademo` directory from which to test, so I've been trying to make it fail with [morra3](https://github.com/algorand-devrel/Reach-Morra-Game/tree/main/morra3) instead.

`morra3`'s  [`index.py` from c4a6b38](https://github.com/algorand-devrel/Reach-Morra-Game/blob/c4a6b382ee954b5f2fce298e4f44d1b07338f837/morra3/client-py/index.py#L80-L88) has the same indentation bug we discovered in [#260](https://github.com/reach-sh/reach-lang/issues/260#issuecomment-920901798), but having fixed that I'm able to run two games simultaneously without issue.

Terminal 1: `../../reach rpc-server`
Terminal 2: `(set environment variables) && source ./venv/bin/activate && python3 -u index.py`
Terminal 3: `(set environment variables) && source ./venv/bin/activate && python3 -u index.py`

Both terminals 2 and 3 complete when I do this, and I can replay as many times as I'd like in each.

Is it possible that you're running `../../reach rpc-run python3 -u index.py` twice instead of just `python3 -u index.py`? That would definitely fail because (as `reach help` says) it would launch the RPC server twice and the two would conflict with each other.

```bash
Usage: reach COMMAND
 where COMMAND is one of
  compile      --- compile an app
  clean        --- delete compiled artifacts
  init         --- set up source files for a simple app
  run          --- run a simple app
  down         --- halt any Dockerized devnets for this app
  scaffold     --- set up Docker scaffolding for a simple app
  react        --- run a simple react app
  rpc-server   --- run a simple Reach RPC server
  rpc-run      --- run an RPC server + frontend with development configuration
  devnet       --- run only the devnet
  upgrade      --- upgrade Reach
  update       --- update Reach Docker images
  docker-reset --- docker kill and rm all images
  version      --- display version
  hashes       --- display git hashes used to build each Docker image
  help         --- show this info
  ```

**Comment by mattaudesse** [comment] 2021-09-28 13:28
Hey @rfustino - I'm going to close this since the discussion seems to have dried up, but please reopen if it's still affecting you. Thanks!

**Closed by mattaudesse** 2021-09-28 13:28 UTC
