### ISSUE TITLE
Solidity Compiler  Error: SPDX license identifier not provided in source file.

### ISSUE THREAD

**Issue by AmbroseHill** [reach-sh/reach-lang#361] opened 2021-11-09 04:28 UTC
**Describe the error**

When compiling a staking contract, the theorems pass but the compiler then throws a solidity error. The error is: 
```
WARNING: Compiler instructed to emit for Algorand, but the conservative analysis found these potential problems:
 * This program could use 765 units of cost, but the limit is 700: [("normal:",28),("preamble:",6),("l0_afterHandler0:",4),("l3_afterHandler1:",4),("l4_afterHandler2:",0),("l7_switchAfterStaker0:",84),("l8_switchAfterStaker1:",6),("l9_switchAfterStaker2:",6),("l10_switchAftersAPI_depositRewards0:",6),("l12_switchAftersAPI_distributeRewards0:",6),("l6_switchK:",0),("l5_afterHandler3:",0),("l15_afterHandler4:",4),("l16_afterHandler5:",4),("l22_afterHandler6:",4),("l24_afterHandler7:",4),("l28_switchAfterNone:",88),("l29_switchAfterSome:",11),("l27_switchK:",0),("l30_ifF:",16),("l32_checkTxnK:",64),("l33_checkTxnK:",48),("l35_switchAfterNone:",39),("l36_switchAfterSome:",8),("l34_switchK:",0),("l39_switchAfterNone:",10),("l40_switchAfterSome:",11),("l38_switchK:",0),("loopBody9:",50),("l59_ifF:",75),("loopBody2:",58),("updateState:",94),("checkSize:",9),("done:",16),("BOT:",2)]

Verifying knowledge assertions
Verifying for generic connector
  Verifying when ALL participants are honest
  Verifying when NO participants are honest
  Verifying when ONLY "Staker" is honest
  Verifying when ONLY "StakingPool" is honest
  Verifying when ONLY "sAPI_depositRewards" is honest
  Verifying when ONLY "sAPI_distributeRewards" is honest
Checked 3018 theorems; No failures!
reachc: The compiler has encountered an internal error:

  The Solidity compiler failed with the message:
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> /tmp/reachc-sol-1400da6b04abf823/compiled.sol

Error: Undeclared identifier. Did you mean "nsvs"?
   --> /tmp/reachc-sol-1400da6b04abf823/compiled.sol:925:17:
    |
925 |     nsvs.v411 = _svs.v411;
    |                 ^^^^

Error: Undeclared identifier. Did you mean "nsvs"?
   --> /tmp/reachc-sol-1400da6b04abf823/compiled.sol:926:17:
    |
926 |     nsvs.v632 = _svs.v632;
    |                 ^^^^



This error indicates a problem with the Reach compiler, not your program. Please report this error, along with the pertinent program, to the Reach team as soon as possible so we can fix it.

Open an issue at: https://github.com/reach-sh/reach-lang/issues

CallStack (from HasCallStack):
  error, called at src/Reach/Util.hs:75:3 in reach-0.1.6-8r3oGglJl9VDVVHXAUm3i8:Reach.Util
  impossible, called at src/Reach/Connector/ETH_Solidity.hs:1421:15 in reach-0.1.6-8r3oGglJl9VDVVHXAUm3i8:Reach.Connector.ETH_Solidity
```

**To Reproduce**
The issue occurs when compiling a staking contract.  I will share the snippet that is causing the compilation error ( Commenting out the below code in the contract allows it to compile) 

```
.api(
    StakingAPI.distributeRewards, () => {
      assume(balance() > 0);
    },
    () => {
      return [0,[0,xusdTok]]
    },
    (apiReturn) => {
      // Try div just returns 0 if totalUsers is 0
      const userReward = tryDiv(totalReward, totalUsers);
      // Iterate through stakeState and add reward to each of them
      const bal = balance();
      var [keepGoing, loopCount] = [true, 0];
      invariant(bal == balance());
      while (loopCount < ARRAYSIZE && keepGoing) {
        assert(loopCount >= 0);
        assert(loopCount < ARRAYSIZE);
        commit();
        Staker.publish();

        const currentUser = users[loopCount];

        if (isSome(currentUser)) {
          const currentAddress = fromSome(currentUser, this);
          const userdata = fromSome(stakeState[currentAddress], {
            stakedXusd: 0,
            rewardsToClaim: 0
          });
          stakeState[currentAddress] = {
            stakedXusd: userdata.stakedXusd,
            rewardsToClaim: userdata.rewardsToClaim + userReward
          };

          loopCount = loopCount + 1;
          continue;
        } else {
          keepGoing = false;
          continue;
        }
      }
      apiReturn(true);
      return [
        totalStake,
        0,
        totalUsers,
        users
      ];
    }
  )
```
Let me know if you want more code snippets.

**Expected behavior**

The contract should compile as it has passed verification.

**Extra information**

Reach Version: 
```reach 0.1.6```

Reach Hashes: 
```reach: 639fa565
reach-cli: 639fa565
react-runner: 639fa565
rpc-server: 639fa565
runner: 639fa565
devnet-algo: 639fa565
devnet-cfx: 639fa565
devnet-eth: 639fa565```

**Comment by jeapostrophe** [comment] 2021-11-09 16:01
Would you please email (or message me on Discord) the full program? I can't reproduce the error from the snippet.

I will say, however, that looking at your program, I am going to try and disallow it completely, because it does an API return in a different consensus step than the call.

Also, your hashes are old... --- a1d29a4b was released yesterday --- and it MAY include a fix for this issue. But I will check, of course.

**Comment by tomxbacked** [comment] 2021-11-30 06:30
**Describe the error**
This has started occuring (again?) on the most recent version.
```
../reach compile ./src/policy.rsh
Verifying knowledge assertions
Verifying for generic connector
  Verifying when ALL participants are honest
  Verifying when NO participants are honest
  Verifying when ONLY "DAO" is honest
  Verifying when ONLY "TestAPI_getLivePolicy" is honest
  Verifying when ONLY "UpdatePolicy_retireApplication" is honest
  Verifying when ONLY "UpdatePolicy_setPolicy" is honest
Checked 280 theorems; No failures!
reachc: The compiler has encountered an internal error:

  The Solidity compiler failed with the message:
Warning: SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> /tmp/reachc-sol-59b291ced02cb307/compiled.sol

Error: Undeclared identifier.
    --> /tmp/reachc-sol-59b291ced02cb307/compiled.sol:1103:9:
     |
1103 |         _apiRet.TestAPI_getLivePolicy = ((_a.svs.v601[_a.msg.v691]));
     |         ^^^^^^^

Error: Undeclared identifier.
    --> /tmp/reachc-sol-59b291ced02cb307/compiled.sol:1122:9:
     |
1122 |         _apiRet.TestAPI_getLivePolicy = (_f.v730);
     |         ^^^^^^^



This error indicates a problem with the Reach compiler, not your program. Please report this error, along with the pertinent program, to the Reach team as soon as possible so we can fix it.

Open an issue at: https://github.com/reach-sh/reach-lang/issues

CallStack (from HasCallStack):
  error, called at src/Reach/Util.hs:75:3 in reach-0.1.7-Jw5jFMAgbXhDKTisTJDxD5:Reach.Util
  impossible, called at src/Reach/Connector/ETH_Solidity.hs:1584:15 in reach-0.1.7-Jw5jFMAgbXhDKTisTJDxD5:Reach.Connector.ETH_Solidity
```
**Expected behavior**

Contract compiles and passes verification.

**Extra information**

Reach Version:
reach 0.1.7-rc.1

Reach Hashes:
```
../reach hashes
reach: b34d92ae
reach-cli: b34d92ae
react-runner: b34d92ae
rpc-server: b34d92ae
runner: b34d92ae
devnet-algo: b34d92ae
devnet-cfx: b34d92ae
devnet-eth: b34d92ae
```

**Comment by jeapostrophe** [comment] 2021-11-30 11:31
@chrisnevers Can you please look into this?

@AmbroseHill If possible, would you share your program with @chrisnevers so he can ensure that his fix doesn't just work on his test program but on yours too? You can DM him on Discord (I am away at a conference)

**Comment by jeapostrophe** [comment] 2021-11-30 11:47
I got it and forwarded it to Nevers :)

**Closed** 2021-12-02 22:04 UTC
