### ISSUE TITLE
js-conflux-sdk npm dependency cannot be fetched when building from CI Docker container

### ISSUE THREAD

**Issue by lorenzopolidori** [reach-sh/reach-lang#714] opened 2022-03-24 15:02 UTC
**Describe the error**

When building a React web app with `@reach-sh/stdlib` as a dependency, the build fails on a CI container. 

This is because the version of `js-conflux-sdk` - one of the `stdlib` dependencies - is specified as `js-conflux-sdk@git+https://github.com/reach-sh/js-conflux-sdk.git#v1_6_0_blockNumber`. This makes the build script to clone the repo using SSH `ssh://git@github.com/reach-sh/js-conflux-sdk.git`, which fails on CI with the following error:

```
Error while executing:
/usr/bin/git ls-remote -h -t ssh://git@github.com/reach-sh/js-conflux-sdk.git
Warning: Permanently added the ECDSA host key for IP address '140.82.121.4' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

This can be temporarily solved replacing `ssh://git@` with `https://` in `package-lock.json` and running `npm ci`.

**To Reproduce**

This is reproducible trying to build a react app with a reach stdlib dependency from within a Docker container. This happens for example on AWS Amplify (CodeBuild): `npm ci` fails with the above error.

**Expected behavior**

The build should succeed without errors.

**Extra information**

Reach version `0.1.9-rc.5`.

I suppose the source of this issue is this line https://github.com/reach-sh/js-reach-stdlib/blob/main/package.json#L46
The version is specified referencing the github repository, which gets resolved with `ssh://git@` when generating `package-lock-json`.

**Comment by jeapostrophe** [comment] 2022-03-25 19:43
I don't understand why that line https://github.com/reach-sh/reach-lang/blob/master/js/js-deps/package.json#L36 which says `git+https://github.com/reach-sh/js-conflux-sdk#v1_6_0_blockNumber` gets turned into `git+ssh`. Maybe @DanBurton or @vinmazzi can help

**Comment by lorenzopolidori** [comment] 2022-04-01 16:59
@DanBurton, @vinmazzi, any updates on this issue? Without a fix, we need to manually replace `ssh://git@` with `https://` in `package-lock.json` to make it work on CI every time we upgrade `@reach-sh/stdlib`.

**Comment by vinmazzi** [comment] 2022-04-25 17:23
@lorenzopolidori I was not able to reproduce the issue.

I have tried with the following npm versions:
- 6.15.16 with node@v14.19.1
- 8.5.0 with node@v16.14.2

All that was tested on a docker ubuntu container through a test react app created with npx.

Would you mind sharing with us the version of npm and node.js that you are using ?

**Comment by lorenzopolidori** [comment] 2022-04-27 14:57
@vinmazzi @DanBurton  
My CI runs on a `amazonlinux:2` docker container with these node versions:
node: v14.19.0
npm: 6.14.16

**Comment by lorenzopolidori** [comment] 2022-04-27 20:38
> This is an open issue on npm v7, but it appears that they do not intend to address it. [npm/cli#2610](https://github.com/npm/cli/issues/2610)
> 
> We will look into ways that we can work around npm's deficiency.

@DanBurton I see this issue is still open and affecting more recent versions of `npm`. In fact, I use the latest stable version `8.8.0` and I am still experiencing the same issue.

**Comment by vinmazzi** [comment] 2022-05-09 13:08
> @vinmazzi @DanBurton My CI runs on a `amazonlinux:2` docker container with these node versions: node: `v14.19.0` npm: `6.14.16`
> 
> However, my `package-lock.json` is created on my MacBook development machine, running node: `12.22.7` npm: `8.8.0`

@lorenzopolidori it is possible that what is causing this issue is the fact that you are creating your package-lock.json with an old version of node.

**Comment by vinmazzi** [comment] 2022-05-09 13:08
@lorenzopolidori it is possible that what is causing this issue is the fact that you are creating your package-lock.json with an old version of node.

**Comment by vinmazzi** [comment] 2022-05-09 13:29
Hey @lorenzopolidori I was able to reproduce the same error using the same version as you.

Could you try to update your local node version to at least the version v14.19.0 ? In that version I was able to create my package-lock.json file.

Also, keep in mind that the version v12 is no longer supported as you can see it here https://github.com/nodejs/release.

Let me know if it fixes, thank you.

**Comment by vinmazzi** [comment] 2022-05-17 14:05
Unfortunately we no longer support node on version v12.
Thanks.

**Comment by lorenzopolidori** [comment] 2022-06-01 09:07
@vinmazzi Thanks for your reply. 
I have upgraded to node `v14.19.1` and npm `8.11.0`. However, when I run `npm install` to recreate my `package-lock.json` from scratch, I still get the same result, i.e. `ssh://git@` instead of `https://`:
```json
"node_modules/js-conflux-sdk": {
      "version": "1.6.0",
      "resolved": "git+ssh://git@github.com/reach-sh/js-conflux-sdk.git#6df5f0538c2077a7e29f0be08205b937499a1040",
}
"js-conflux-sdk": {
    "version": "git+ssh://git@github.com/reach-sh/js-conflux-sdk.git#6df5f0538c2077a7e29f0be08205b937499a1040",
    "from": "js-conflux-sdk@git+https://github.com/reach-sh/js-conflux-sdk.git#v1_6_0_blockNumber",
}  
```

**Comment by lorenzopolidori** [comment] 2022-08-08 21:41
@vinmazzi I can confirm this is still an issue and it is affecting also other developers working with me and running the lasted versions of node 14 and npm.

**Comment by jeapostrophe** [comment] 2022-08-10 08:20
@DanBurton Can you please create a fresh Jira task for this and assign to yourself? I have two ideas about solutions...
1. Update to a newer version of `js-conflux-sdk` that includes our patches and is on npm so we don't need to do this
2. Make an npm release of our patch so we don't need to go through `git+https`

Maybe you have other ideas?

**Comment by DanBurton** [comment] 2022-08-11 20:55
Acknowledged. I've had the same 2 ideas and I presume we'll go with the latter, but I'll look into both options.

**Comment by jeapostrophe** [comment] 2022-11-02 18:01
This was worked on in #1437 but that failed because of weird problems with other changes to CFX. I think something else should be done in the interim, like the npm release.

**Comment by jeapostrophe** [comment] 2022-11-07 09:24
I merged a change that uses a forked version of the package, hosted on NPM. Sorry for it taking so long to do this.

**Closed by jeapostrophe** 2022-11-07 09:24 UTC
